### ISSUE TITLE
Change ReportMode in "releaseConfig" in Catcher dynamically

### ISSUE THREAD

**Issue by Eerey** [jhomlala/catcher#112] opened 2020-09-09 11:41 UTC
Hi,

how can i dynamically change the ```dart   final ReportMode reportMode;``` in ```CatcherOptions``` ?

Dependent on a user input (checkbox), i want to switch between DialogReportMode and SilentReportMode in the CatcherOptions.

Currently, my ```Catcher```-Widget is in the main Method as the first widget:

```dart
  Catcher(
    MyFlutterApp(),
    debugConfig: catcher_config.config["debug"],
    profileConfig: catcher_config.config["profile"],
    releaseConfig: catcher_config.config["release"],
  );
```

Cheers

**Comment by jhomlala** [comment] 2020-09-19 19:29
Duplicate of https://github.com/jhomlala/catcher/issues/110
You can update Catcher config in runtime. Please check readme: https://github.com/jhomlala/catcher#update-config

**Closed by jhomlala** 2020-09-19 19:29 UTC
