### ISSUE TITLE
Incompatibility with AndroidX

### ISSUE THREAD

**Issue by vico-aguado** [jhomlala/catcher#5] opened 2019-02-12 04:11 UTC
I update your pubspec.yaml to:
 fluttertoast: ^2.2.11
  device_info: ^0.4.0
  package_info: ^0.4.0+1
  mailer: ^2.2.0
  dio: ^1.0.14
  flutter_local_notifications: ^0.5.1
  flutter_mailer: ^0.4.0+1
  logging: ^0.11.3+2

And works fine with Android 28    :)

**Comment by jhomlala** [comment] 2019-02-12 15:49
Can you tell me which library causes incompatibility issues with AndroidX?

**Comment by vico-aguado** [comment] 2019-02-12 15:55
Sure!!

package_info: ^0.4.0 -> package_info: ^0.4.0+1
flutter_local_notifications: ^0.4.4+2 -> flutter_local_notifications: ^0.5.1
flutter_mailer: ^0.3.0 -> flutter_mailer: ^0.4.0+1

Only these ones. ;)

**Comment by jhomlala** [comment] 2019-02-12 16:40
I've updated dependencies just like you said and this will make build fail because of AndroidX.

So I've created new project, updated compileSdkVersion and targetSdkVersion to 28 and added Catcher 0.0.10. There was build success. So from my perspective Catcher 0.0.10 is working fine with AndroidX.

Can you try reproduce AndroidX error with Catcher 0.0.10 and log your steps in comment? Thanks

**Comment by vico-aguado** [comment] 2019-02-12 16:51
I do, but still this error:
/Users/user/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-0.4.5/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:17: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/user/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-0.4.5/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java:139: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class FlutterLocalNotificationsPlugin
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_local_notifications:compileDebugJavaWithJavac'.
WARNING: This version of device_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Finished with error: Gradle task assembleDebug failed with exit code 1


My solution is edit your pubspec.yaml and works fine! :)

**Comment by jhomlala** [comment] 2019-02-12 17:53
In my case:

Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+1\android\src\main\java\io\flutter\plugins\packageinfo\PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Program type already present: android.support.v4.os.ResultReceiver$1
         *********************************************************
WARNING: This version of package_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\jhoml\Documents\Projekty\catchergit\example\build\app\intermediates\transforms\dexBuilder\debug\29.jar
  Program type already present: android.support.v4.os.ResultReceiver$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by jhomlala** [comment] 2019-02-12 18:01
Can you fork Catcher and setup dependencies? I'll try build your version.

**Comment by jhomlala** [comment] 2019-02-12 18:17
Okay I've probably found solution. Can you run version from this branch: https://github.com/jhomlala/catcher/tree/fix/androidx ?

**Comment by jhomlala** [comment] 2019-02-13 16:19
Fixed in 0.0.11. If you're still facing this problem, open new issue.

**Closed by jhomlala** 2019-02-13 16:19 UTC

**Comment by aimanbaharum** [comment] 2019-03-12 05:39
Is it safe to say now that if someone has issues migrating their apps to AndroidX, don't use this changes instead use 0.0.10, the last library stable version before the AndroidX changes?

https://pub.dartlang.org/packages/catcher#-changelog-tab-
