### ISSUE TITLE
Couldn't use report mode becuase you didn't provide navigator key. Add navigator key to use this report mode.

### ISSUE THREAD

**Issue by praveenb** [jhomlala/catcher#109] opened 2020-08-24 20:12 UTC
Hi, 

Im  using 
Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)

and using Plugin version
catcher: 0.3.2

Pls see below code how i use Catcher 

```
  ReportHandler emailReportHandler = EmailManualHandler(["applogs@abc.com"],
      enableDeviceParameters: true,
      enableStackTrace: true,
      enableCustomParameters: true,
      enableApplicationParameters: false,
      sendHtml: true,
      emailTitle: 'Application Crash Report',
      emailHeader: Texts.EMAIL_TEMPLATE,
      printLogs: true);

  var explicitMap = {
    "FormatException": ConsoleHandler(),
    "RenderFlex": ConsoleHandler(),
    "Exception": ConsoleHandler(),
    "MissingPluginException": ConsoleHandler(),
   };

  var explicitReportModesMap = {
    "FormatException": SilentReportMode(),
    "RenderFlex": SilentReportMode(),
    "Exception": SilentReportMode(),
    "MissingPluginException": SilentReportMode(),
  };


  Map<String, dynamic> customParams=
  {
    "AppVersion": '$appVersion',
    "Host": 'Test',
  };
 

  CatcherOptions debugOptions = CatcherOptions(DialogReportMode(), [ConsoleHandler(enableCustomParameters: false,),emailReportHandler], customParameters: customParams,explicitExceptionHandlersMap: explicitMap,explicitExceptionReportModesMap: explicitReportModesMap,);

  CatcherOptions releaseOptions = CatcherOptions(DialogReportMode(), [ConsoleHandler(enableCustomParameters: false,),emailReportHandler],customParameters: customParams,explicitExceptionHandlersMap: explicitMap,explicitExceptionReportModesMap: explicitReportModesMap,);

  catcher = Catcher(new MediaQuery(
      data: new MediaQueryData.fromWindow(window),
      child: new Directionality(
          textDirection: TextDirection.ltr,
          child: MaterialApp(
              debugShowCheckedModeBanner: true,
              builder: (BuildContext context, Widget widget) {
                Catcher.addDefaultErrorWidget(
                    showStacktrace: true,
                    customTitle: 'An unexpected error occurred forcing the application to stop.',
                    customDescription: " Please help us fix this by sending us error data.\n\nApplication has been able to get error state. See details below");
                return widget;
              },
              navigatorKey: Catcher.navigatorKey,
              title: Texts.TITLE,
              home: _defaultHome,
              theme: ThemeData(
                  primarySwatch: CompanyColors.black,
                  accentColor: Palette.appColor,
                  textTheme: TextTheme(
                      body1: TextStyle(
                          fontWeight: FontWeight.normal,
                          fontSize: 18.0,
                          color: Colors.black))),
              routes: <String, WidgetBuilder>{
                '/login': (context) => new LoginPage(),
                '/home': (context) => new HomePage(),
              }))),
      debugConfig: debugOptions,
      releaseConfig: releaseOptions,
      enableLogger: true); 
}
```

Whenever a crash occurred, it shows this in Run console
 `Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.`

Same in iOS and Android side.

Kindly let me know how to solve this issue.

**Comment by jhomlala** [comment] 2020-09-05 14:17
Please upgrade to latest Catcher version which is 0.3.17. Also share runnable code.

**Comment by praveenb** [comment] 2020-09-15 10:37
I did upgrade but still same.

**Comment by jhomlala** [comment] 2020-09-19 19:16
Please share reproducible code. The code from above doesn't show anything wrong.

**Comment by praveenb** [comment] 2020-10-01 15:20
When this kind of below error happen, (I see below error, only when removed wrapping with Catcher )

```
Another exception was thrown: type 'WidgetDropdownValueBloc<dynamic>' is not a subtype of type 'WidgetDropdownValueBloc<DropDownElementData>'

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
type 'WidgetDropdownValueBloc<dynamic>' is not a subtype of type 'WidgetDropdownValueBloc<DropDownElementData>'
```
Instead of above error in log, it just show as below
Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.

Also,  At times it happens when app using a null item, Ex: listitems variable, which got null 
`listItems.length`

Then its just shows Couldn't use report mode. 

To see actual error I have to remove wrapping with Catcher at root widget in main.

**Comment by jhomlala** [comment] 2020-10-24 08:15
There's something wrong with navigator key in your project. Please share your code which can reproduce this problem or I will close this issue.

**Comment by hhstore** [comment] 2020-11-06 05:40
+1. any solution? 

## my codes like this : 


```dart


import 'package:auto_route/auto_route.dart';
import 'package:fimber/fimber.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:oktoast/oktoast.dart';
import 'package:provider/provider.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:catcher/catcher.dart';

import 'package:starter/proto/config/config.dart';
import 'package:starter/std/util/log.dart';
import 'proto/config/locale.dart';
import 'proto/config/theme.dart';
import 'proto/provider/provider.dart';
import 'std/page/404/not_found.dart';
import 'core/router/router.gr.dart';
import 'core/router/router_guards.dart';
import 'proto/l10n/generated/l10n.dart';

void main() async {
  Provider.debugCheckInvalidValueType = null;
  WidgetsFlutterBinding.ensureInitialized();

  /// logging:
  Fimber.plantTree(DebugTree());

  ///
  /// config init:
  ///
  await AppConfig.init();

  /// logger print:
  logger.i('waiting to start app!');

  /// STEP 1. Create catcher configuration.
  /// Debug configuration with dialog report mode and console handler. It will show dialog and once user accepts it, error will be shown   /// in console.
  var debugOptions = CatcherOptions(DialogReportMode(), [ConsoleHandler()]);

  /// Release configuration. Same as above, but once user accepts dialog, user will be prompted to send email with crash to support.
  var releaseOptions = CatcherOptions(DialogReportMode(), [
    EmailManualHandler(['support@email.com'])
  ]);

  /// STEP 2. Pass your root widget (MyApp) along with Catcher configuration:
  Catcher(CoolApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);

  ///
  /// app run:
  ///
//  runApp(MyApp());
}

class CoolApp extends StatefulWidget {
  @override
  CoolAppState createState() => CoolAppState();
}

class CoolAppState extends State<CoolApp> {
  final title = 'Flutter Starter';
  final primaryColor = Colors.pink;
  final isDebug = false;

  final catcherKey = Catcher.navigatorKey;

  @override
  Widget build(BuildContext context) {
    return OKToast(
      key: catcherKey,
      child: MultiProvider(
        key: catcherKey,

        /// state management:
        providers: providers,

        /// sub:
        child: Consumer2<AppTheme, AppLocale>(
          key: catcherKey,
          builder: (context, theme, locale, child) {
            ///
            ///
            var app = MaterialApp(
              /// STEP 3. Add navigator key from Catcher. It will be used to navigate user to report page or to show dialog.
              navigatorKey: catcherKey,

              ///
              debugShowCheckedModeBanner: isDebug,

              ///
              theme: theme.themeData(),

              /// 多语言支持: 关键代码行
              locale: locale.locale,

              /// app name:
              title: title,

              /// app core:
              builder: ExtendedNavigator.builder<AppRouter>(

                  /// route list:
                  router: AppRouter(),

                  ///
                  initialRoute: '/',

                  /// 404 page:
                  onUnknownRoute: (settings) {
//                      ExtendedNavigator.root.pushUnknownPage();
                    return MaterialPageRoute<void>(
                      settings: settings,
                      builder: (context) => UnknownPage(),
                    );
                  },

                  /// route auth:
                  guards: [AuthGuard()],

                  ///
                  builder: (ctx, extendNav) => Theme(
                        data: ThemeData(
                          primaryColor: primaryColor,
                        ),
                        child: extendNav,
                      )),

              /// multi language:
              localizationsDelegates: const [
                /// intl gen:
                S.delegate,

                /// 下拉刷新
                RefreshLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
              ],

              ///
              supportedLocales: S.delegate.supportedLocales,
            );

            return RefreshConfiguration(
              hideFooterWhenNotFull: true,

              /// app core:
              child: FlutterEasyLoading(
                child: app,
              ),
            );
          },
        ),
      ),
    );
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
  }

  @override
  void didUpdateWidget(CoolApp oldWidget) {
    // TODO: implement didUpdateWidget
    super.didUpdateWidget(oldWidget);
  }

  @override
  void didChangeDependencies() {
    // TODO: implement didChangeDependencies
    super.didChangeDependencies();
  }
}


```


## error logs: 


```bash


flutter: [2020-11-06 13:35:00.389603 | Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.
flutter: [2020-11-06 13:35:00.495502 | Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getIosDeviceInfo on channel plugins.flutter.io/device_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannelDeviceInfo.iosInfo (package:device_info_platform_interface/method_channel/method_channel_device_info.dart:25:22)
#3      DeviceInfoPlugin.iosInfo (package:device_info/device_info.dart:34:66)
#4      Catcher._loadDeviceInfo (package:catcher/core/catcher.dart:221:20)
#5      Catcher._configure (package:catcher/core/catcher.dart:79:5)
#6      new Catcher (package:catcher/core/catcher.dart:68:5)
#7      main (package:starter/main.dart:46:3)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/fut<…>
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359:49)
#3      PackageInfo.fromPlatform (package:package_info/package_info.dart:43:25)
#4      Catcher._loadApplicationInfo (package:catcher/core/catcher.dart:290:19)
#5      Catcher._configure (package:catcher/core/catcher.dart:80:5)
#6      new Catcher (package:catcher/core/catcher.dart:68:5)
#7      main (package:starter/main.dart:46:3)
#8      _rootRunUnary (dart:async/zone.dart:1198:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._<…>
flutter: [2020-11-06 13:35:00.508255 | Catcher | WARNING] Couldn't use report mode because you didn't provide navigator key. Add navigator key to use this report mode.

```

**Comment by hhstore** [comment] 2020-11-06 05:45
- i try to add  `key` to OKToast().key and `MultiProvider().key`, but not work. 


![image](https://user-images.githubusercontent.com/3252130/98330641-cd9e6f00-2035-11eb-85c1-946bfb0363c8.png)

- catcher auto call `runApp()`, is there a connection here?

**Comment by jhomlala** [comment] 2021-02-06 20:22
You can init Catcher with your own runApp since version 0.0.40.
Catcher's navigator key is working fine, but there can issues with other libraries.

**Closed by jhomlala** 2021-02-06 20:22 UTC
Labels: help wanted

**Comment by kapiltk007** [comment] 2023-03-09 10:45
This will works fine for me... Thank you
